# Generated by Django 4.2.7 on 2023-12-13 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="", verbose_name="Изображения для Меню"
                    ),
                ),
            ],
            options={
                "verbose_name": "Изображение",
                "verbose_name_plural": "Изображения",
            },
        ),
        migrations.CreateModel(
            name="JoinUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, verbose_name="Введите вашу почту"
                    ),
                ),
            ],
            options={
                "verbose_name": "Подписанные на рассылку",
                "verbose_name_plural": "Подписанные на рассылку",
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reg_name", models.CharField(max_length=30)),
                ("slug", models.SlugField(unique=True)),
            ],
            options={
                "verbose_name": "Область",
                "verbose_name_plural": "Область",
            },
        ),
        migrations.CreateModel(
            name="Sight",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sight_name",
                    models.CharField(
                        max_length=50, verbose_name="Достопримечательность"
                    ),
                ),
                ("description", models.TextField(verbose_name="Описание")),
                ("price", models.IntegerField(default=0, verbose_name="Цена")),
                (
                    "duration_days",
                    models.PositiveIntegerField(default=0, verbose_name="Длительность"),
                ),
                ("slug", models.SlugField(unique=True)),
                ("image", models.ImageField(upload_to="", verbose_name="изображение")),
                (
                    "currency_type",
                    models.CharField(
                        choices=[("$", "Доллар"), ("C", "Сом"), ("€", "Евро")],
                        default="C",
                        verbose_name="Тип валюты",
                    ),
                ),
                (
                    "province",
                    models.ForeignKey(
                        max_length=40,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tours_kg.region",
                        verbose_name="Место расположения",
                    ),
                ),
            ],
            options={
                "verbose_name": "Достопримечательность",
                "verbose_name_plural": "Достопримечательности",
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=30, verbose_name="Имя пользователя"),
                ),
                ("reviews", models.TextField(verbose_name="Отзыв")),
                ("rating", models.PositiveIntegerField(verbose_name="Оценка")),
                (
                    "sight",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tours_kg.sight",
                        verbose_name="Достопримечательность",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзывы",
                "verbose_name_plural": "Отзыв",
            },
        ),
        migrations.CreateModel(
            name="BookNow",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=30, verbose_name="Ваше имя")),
                (
                    "surname",
                    models.CharField(max_length=30, verbose_name="Ваша фамилия"),
                ),
                (
                    "phone",
                    models.CharField(max_length=15, verbose_name="Ваш номер телефона"),
                ),
                ("email", models.EmailField(max_length=254, verbose_name="Ваша почта")),
                (
                    "quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Количество забронированых туров"
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата бронирования")),
                (
                    "sightseeing",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="tours_kg.sight",
                        verbose_name="Тур",
                    ),
                ),
            ],
            options={
                "verbose_name": "Бронь",
                "verbose_name_plural": "Брони",
            },
        ),
    ]
