# Generated by Django 4.0.1 on 2022-01-13 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='date',
            field=models.DateTimeField(null=True, verbose_name='Дата бронирования'),
        ),
    ]
