# Generated by Django 4.0.1 on 2022-01-13 13:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JoinUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Введите вашу почту')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviews', models.CharField(max_length=1000, verbose_name='Отзыв')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзыв',
            },
        ),
        migrations.AlterModelOptions(
            name='booknow',
            options={'verbose_name': 'Бронирование', 'verbose_name_plural': 'Забронировать'},
        ),
        migrations.AlterModelOptions(
            name='region',
            options={'verbose_name': 'Область', 'verbose_name_plural': 'Область'},
        ),
        migrations.AlterModelOptions(
            name='sight',
            options={'verbose_name': 'Достопримечательность', 'verbose_name_plural': 'Достопримечательность'},
        ),
        migrations.AddField(
            model_name='booknow',
            name='date',
            field=models.DateTimeField(default=1, verbose_name='Дата бронирования'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='booknow',
            name='for_anonymous_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='region',
            name='slug',
            field=models.SlugField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sight',
            name='sight_name',
            field=models.CharField(default=1, max_length=50, verbose_name='Достопримечательность'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sight',
            name='slug',
            field=models.SlugField(default=11, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booknow',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Ваша почта'),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='name',
            field=models.CharField(max_length=30, verbose_name='Ваше имя'),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='phone',
            field=models.CharField(max_length=15, verbose_name='Ваш номер телефона'),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Количество забронированых туров'),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='sightseeing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours_kg.sight', verbose_name='Тур'),
        ),
        migrations.AlterField(
            model_name='booknow',
            name='surname',
            field=models.CharField(max_length=30, verbose_name='Ваша фамилия'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='duration',
            field=models.PositiveIntegerField(default=0, verbose_name='Длительность'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='price',
            field=models.IntegerField(default=0, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='sight',
            name='province',
            field=models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='tours_kg.region', verbose_name='Место расположения'),
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70, verbose_name='Как к вам обращаться?')),
                ('user_phone', models.CharField(max_length=20, verbose_name='Ваш номер телефона')),
                ('orders', models.ManyToManyField(related_name='orders', to='tours_kg.BookNow', verbose_name='Ваши брони')),
            ],
            options={
                'verbose_name': 'Пользователи',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
