# Generated by Django 4.0.1 on 2022-01-11 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookNow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, verbose_name='ИМАИЛ')),
            ],
        ),
        migrations.CreateModel(
            name='Sight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='Описание')),
                ('price', models.IntegerField(default=0)),
                ('duration', models.PositiveIntegerField(default=0)),
                ('province', models.ForeignKey(max_length=40, on_delete=django.db.models.deletion.CASCADE, to='tours_kg.region')),
            ],
        ),
        migrations.RemoveField(
            model_name='province',
            name='provi_name',
        ),
        migrations.DeleteModel(
            name='City',
        ),
        migrations.DeleteModel(
            name='Province',
        ),
        migrations.AddField(
            model_name='booknow',
            name='sightseeing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tours_kg.sight'),
        ),
    ]
