# Generated by Django 4.0.1 on 2022-01-14 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='quantity',
            field=models.IntegerField(default=1, verbose_name='Количество забронированых туров'),
        ),
    ]
