# Generated by Django 4.0.1 on 2022-01-14 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0002_alter_booknow_sightseeing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='sightseeing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='book_sight', to='tours_kg.sight', verbose_name='Тур'),
        ),
    ]
