# Generated by Django 4.0.1 on 2022-01-14 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0002_alter_booknow_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество забронированых туров'),
        ),
    ]
