# Generated by Django 4.0.1 on 2022-01-14 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0004_alter_booknow_sightseeing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booknow',
            name='sightseeing',
            field=models.CharField(blank=True, choices=[('SC', 'Сары-Челек'), ('IK', 'Ыссык-Куль'), ('AK', 'Ала-коль'), ('AA', 'Ущелье Ала-Арча'), ('JO', 'Джети-Огуз')], max_length=100, null=True, verbose_name='Тур'),
        ),
    ]
