# Generated by Django 4.0.1 on 2022-01-15 11:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tours_kg', '0006_latestnews_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LatestNews',
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
